//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ms.Cms.Models
{
    [Table("Bricks", Schema = "Cms")]
    public abstract partial class Brick
    {
        public long Id { get; set; }
        
        [MaxLength(50)]
        public string Title { get; set; }

        public float Width { get; set; }

        public byte Order { get; set; }

        [MaxLength(50)]
        public string ContentTitle { get; set; }

        //[ForeignKey("WallId")]
        public virtual Wall Wall { get; set; }

        public long WallId { get; set; }
    }

}
