//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace Ms.Cms.Models
{
    public partial class CmEntities : DbContext
    {
        public CmEntities()
            : base("Ms.Cms")
        {
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    //throw new UnintentionalCodeFirstException();
        //    modelBuilder.Entity<Brick>().ToTable("Bricks", "Cms");
        //    modelBuilder.Entity<Wall>().ToTable("Walls", "Cms");
        //    modelBuilder.Entity<SceneTemplate>().ToTable("SceneTemplates", "Cms");
        //}

        public DbSet<Brick> Bricks { get; set; }
        public DbSet<Wall> Walls { get; set; }
        public DbSet<SceneTemplate> SceneTemplates { get; set; }
    }
}
