//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ms.Cms.Models
{
    public partial class LinkableBrick : Brick
    {
        public long? LinkedBrickId { get; set; }

        //[ForeignKey("LinkedBrickId")]
        public virtual Brick LinkedBrick { get; set; }
    }
    
}
