//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Ms.Cms.Models
{
    public partial class MapBrick : Brick
    {
        [MaxLength(100)]
        public string GpsLocation { get; set; }

        public int? Height { get; set; }

        public int? Zoom { get; set; }
    }
    
}
