//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ms.Cms.Models
{
    [Table("SceneTemplates", Schema = "Cms")]
    public partial class SceneTemplate
    {
        public SceneTemplate()
        {
            this.Walls = new HashSet<Wall>();
        }
    
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string IconUrl { get; set; }

        [NotMapped]
        public ICollection<Wall> Walls { get; private set; }
    }
    
}
