//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;

namespace Ms.Cms.Models
{
    public partial class SharedBrick : Brick
    {
        public long? SharedBrickId { get; set; }

        public Brick Share
        {
            get
            {
                return new CmEntities().Bricks.Where(b => b.Id == this.SharedBrickId).FirstOrDefault();
            }
        }
    }
    
}
