//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ms.Cms.Models
{
    [Table("Walls", Schema = "Cms")]
    public partial class Wall
    {
        public Wall()
        {
            this.Bricks = new HashSet<Brick>();
        }

        public long Id { get; set; }

        public Guid OwnerId { get; set; }

        [MaxLength(50)]
        public string Title { get; set; }

        public float Width { get; set; }

        public byte Order { get; set; }
    
        public ICollection<Brick> Bricks { get; private set; }
    }
    
}
