// <auto-generated />
namespace Ms.Cms.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206102007082_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1bW2/bNhR+H7D/IOipHVDLydYiLZwWuTdYLkWcdsBeCkY6tolSlEpSWby/tof9pP2FkbqZ1F12ajvd3mKK5+O58Yj8dPLPX3+P3j34xLoHxnFA9+2dwdC2gLqBh+l0347E5MWe/e7tjz+MTjz/wfqUzdtV86Qk5fv2TIjwjeNwdwY+4gMfuyzgwUQM3MB3kBc4u8PhnrMzdEBC2BLLskY3ERXYh/iH/HkUUBdCESFyGXhAeDoun4xjVOsK+cBD5MK+fckHRz4fJBNt64BgJJUYA5n01Gj4Wmlk52vJ1U6kVmJ+Ow8hXnHfPmTY/SIXueOCIVfs24JFoItIoV9hbgzIoQ8sCIGJ+Q1MUqBzz7YcU84pCuZimozSRf5FxatfbOsqIgTdETkwQYSDbYWv3oxFwOAMKDAkwPuAhABGlSzEtqQ+eRO+6uaW185wV7nFQZQGAgkZ7ZLiBTVvsSCQaToWTGaObZ3iB/AugE7FLNf2Ej1kIy9l+nykWOYZpD7VjEt+Ny/6G/bELF9ULkmgwj/NGNfMA5ZhHM5FfwSZt0L6eTMeQIS0Z0gB4wrd42kc1Qo027oBEj/kMxwme2qgHnyOt4HcbKcs8G8Cks5Phz/fIjYFITUJys/GQcTcgh4jZ7HPGndfrNT/m83I2T/k4gtdzyLs9c7a/9KGrU34LKWXS/ksratSPtsOS6X8e+GT9KVziDik7lJaJaON/lHCPeMq/+wV2M6G3KA/A1ZtiWaj04hxicKlfXEW8ovATfdUL5fsDFfN9feApzOh1ZOfd/tC/B4Efg+AzmE5k4kKbL60W899NIULzEVDvVxBvRM/FI3KtWTMbeCuIH2B6RdlwtLeUQDgxRN7+aepUGmYldXKUPqzMXtRu2onlSpZ/cyV6trYlW/NW/BDqf8GDtBre0/2racVSrsB/cg2VccPOA9cHOeYdgjL3oam4ifUsxpejYudkxwuLyMicEiwK5eVVdYuxvya"
                       + "HgMBAdaBK+JL5hHiLvLKDpOqe100yc+lpTJgqvJTaQWZdsDUmQ4RecRXdz9MRTlHMXVxiEi9EwoiHRNbmZiDF58cQwhUnTfrDe6yanZ7KK+cL1BweptPRo6WO80pVV+y6sLaoX4tglwo423B7rJK11QaDgY7j5NNrbqsIbdavd5Fh8I7cQ0Jl1Q2dTeXEsCyu7ofj2MolzE1fQyicDNYFMj6M0SFuNpZVdJJEWwRNl6TVSjme7QIpznEVCi/zmgzKm47xdg0V/hc+dzoUnCbC7MGkOlXLPWmRR2sbTgOlW3vWIh6lqJWs3oWnVXclL3n892woFadhFvNOFinhoQdyVtYKI8gGimbjljjhJE9ejHuT736CYbj8goGNtc2X0kETF48Ck8VAefBKWZcHCOB7pA6FB15fnla697PFtL3cDlm2WbMZqu/06uqzkoPysSV7rdTaYqvqmxMJxV2UVksZsERQazidHsUkMin9cW+XjonknSIfLA7TnpI1lHSoe4YKTekY6RDPexJuCHDmmSojDFyCpEovZNKoS6dQM286ZRVtUW2a1otiJP+uVUj922SKyGidPlkpBJB7lMPx6fDT4hEJgemQxxj7jLsY4qkad8irL1iofFb33UwdB5ve6ORM4VbHguDldRhjAc9YpsyjUZ007HuKAnZqGMkI90yZMHSbm9+GLTnlueIQbEaMPqDbrEx6d7tjY/G+25PdEre1Nnp7fVlzoFvsScXPP32+tGkkbbHmZXSBZZFB2ohYKoDVODQtilK51z9fT15ZoYr1vT5tsfpKV6X6jDM7hcdynzSw7KUlTZMq2GqN3aNK3B0yxeYhm9iMVJb4rbIb28C55+4DDWywTUHusSQFafkq+dMWYERG6XsVHvvYomuSqbYlnTQPfYUVTWecwH+QE0YjL+SI4KlvYsJl4jiCXBxG3wB1Yc5HO4t3wOZ9x9x7pEKGm7jrVh3eIqV9a19V30bicwuqojirxHgGG2CVRFc"
                       + "5UsxvUfMnSFW6p9aoWGKASKrtUsJTOexLxtBOn/Pr/pc94QT4rsJYBmkqkf1sSw0WlCz2PTUT29ay/R65qOH5321qej4qrQz7u9apaGrYGXfdq4lxCu6rsre7gJU2aC0HFThGtDk8N29xyo7G24j+jYviqWyvdAm1APr8Vt/NtXsk15O19jfs46uizq+4ck38XQMV2UPTQElOequKfDdA/IYkY9N67LY1jTWlL7B11yjjX81qemPSS5E6os9l/FNSlhlc0l12059104VcE03RWNTTntPTtVKxb6etfbtlDp1GvtRDD9qBNkTaM3pqHpdOVnB5B5tNmWyQO5I7d8hZVXgeLqAUNwsBdfYi/mcczoJsspQ0CibUjg3XIJAntyoB0weYZAr5GMXOI97jPPPHHfgndPrSISRkCaDf0fmujNUaWlaP+4lMnUeXYdx3/pjmCDVxNIEuKaHESZervdpxcGyBkLVrPT6qGIp1DVyOs+RrgLaESh1X15q8z1+TcfoHup1a/eh6bHRMUZThnyeYizk5U+Zfp7/8PZffPeCmdA7AAA="; }
        }
    }
}
