// <auto-generated />
namespace Ms.Cms.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206110230117_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1cW2/bNhR+H7D/IOipHVDLybYiLZwWuTdYnBRx2gJ7CRiJdohKlCbSWby/tof9pP2FkbqSIqmbE0fN+hbz8vHceEiec5R///5n8v4+8K07GBMU4l17azS2LYjd0EN4sWsv6fzVjv3+3Y8/TI684N76nI/b5uPYTEx27VtKo7eOQ9xbGAAyCpAbhySc05EbBg7wQmd7PN5xtsYOZBA2w7KsyeUSUxTA5Af7eRBiF0Z0Cfxp6EGfZO2sZ5agWucggCQCLty1p2R0EJBROtC29nwEGBEz6M87UjR+wymyi7XYakeMKrq6WkUwWZHBuhBDcQgb9BtcSQ2s6WMcRjCmq0s4zyaeerblyPOc6sRimjCHr83+wvT1L7Z1vvR9cOOzhjnwCbSt6PXbGQ1jeMKoigGF3kdAKYwxnwsT2jMZvI1etxPDG2e8zcXgAIxDCijTrkJ4hcyLP9niJ0vklfTyXxpyW+CchXjRzHcLIDZVwvl5uxnnHNyhRcJzBfEL8LltXUI/6SW3KEpNbMR7rlOrsI7jMLgM/Wx82np9BeIFpIyQUOmahcvYrVAxcUqbq7VEjvPdECUyE6muazxXiPowh5jRmPk9pll0D70ziBf0toCZgvu85Vfm/D5hxLwkm0PjJRRXTX/XL/oFefS2WJQt6cPuVh97MM4x9le0BYLR3jOD7mPvuVFr7D3fCm2p2I+R+1W/7ZKu62QPCGSUrcq2E7rW2nYJDjtlbgiNgUsz9X7fh//XLVRBYBcXyuT8NBJgxt3Z+9Ueef22XtUDaHZlr633gQZ+tv32AYGZcAuS7Frh8MkdFcL+7KSR1oxcgr/CWM+JwKNTizEFUW9ZnETkLHSzrdxJJFvjdY30A0SLW2q8l7WB+D0Mgw4ArdVywiwUxqveYj0NwAKeIUJrNuEa5B0FEa0lrsFirkJ3jdlnCH/lLPSWDgeAXjKwk3zqfJSAqXVVEtHX0ujScxkHKY7MPHItv5Zc"
                       + "jq5gEDH6n+Aq0eut1ueA6+pPNUS7If4UP5Uf3yMkdFFiY8IZea0LCRxhzzLfjMt9k56i06VPUeQjly26a/+kSEGLVlxwS7TsWi7DbdlVA7rAh9CHFFp7Lk2CNweAuMBTpc/k4MktzOZgzO+RwGc3HX4FRpiqBoqwiyLgG4muzGhp1JyiArvacwgjiPkV1yj3NosWL0h15WKBioyaRDJxBLupNyfhZmUyAN01S/Hk7e1J92Cqt86nNyeV5g2Ykyr3NovmN/InsSbz4WeyhhYnYWkclQtBe5trPkWbLHo8Gm0pC/SypUZaNmBajVJvQ0PldrUBg0vPSP7eZTNgnL9/A5J0IEgUM+PjZ5CKrpbYVnnWyqeYYj/y9Cwiq8xOfVbD5DywpMzWXIVNpOcXNiMLxY2uCicIVOYnj6sJA9SoW1WztVeNgvJCYIpl1F4uhPm5vqpOXeamBadi/EDl1HQGNp2CAqW5dmtY1Zx7TaLqwWnN80NlvKW77uiwu4ml2TU34tWIKb9XFz6jzOo5aVovT/85hvzfZAqiiF35hXxg1mLN0mTgwatZ96xfkGI4LtEk/wpqi5VoGLOHfqWXh/48eIxiQg8BBTeAP0IOvEAd1uwh85UkR6lqLXc6+XD+dxYcElOiI63fKEV3zLgJ+HGUBI6rO16dlyRhgQ9izYvyIPSXATYfi+bZUhJRhJE6OuLlyUQFL+/oiJflFBW4rF1FmzgVISvnsqJG5c4sG0Urk0kdWH+L0bnfFgajn/Y49lK81EQI4/PNjJMFMkSUrKk9RpZ6EDGypg72laYeJNNKmwZjVZnD729WZXC7u20Z5j2OcaXJAnF+2qJFYL7dQ8m76zPwl3KeQoQ4RMSNUYAwYKw9hlo76ULIQTxrZYi5luFqo8jmDFwXUuZIhJE6Oug2ywZJ2s3a2qOkCSERI21pZyFlJm249iGlpgZuI1IaTIIRO9rpRk7JDVc/Qm5uONpRpClmEIcryyJPOWBJlrnU"
                       + "4cpRDtAOR5ja2ZX4pQjUENrUK6gSnR6Slk4J//ti/kJWV0Lpy6Hr6Vt8Lpkw5FotEUru6cBZlu+RWDPkgJ7sGVeJXq8ZV9LXLSRIreJL5vnDNeCiDEEiI2/csKKVqGp1SLF6EV2tRFEnWUSz+VMLJcSZDrEtJqA75PHw5mxFKAxGfMBo9od/4CPGbzlgCjCaQ0Kvwq+QfzYyHu/0/2SjKE0lxPM1odun/27jBi0QZ7+xJrfPFw7yJxdLjP5YQpQgzhH3hOt/fpGTv/b3F80oA//u4bEUWflkoafApWosfAdi9xbESnHxGvXUMQT+etXUFOHVA1qBrpDhGzaDZ6NAFURXEf9QHEoF7z33jlgYntP1IgD3L7tSo6mq1vKZ1FCvUzRd4bJryXSP6ZrKZlXabYC0RcD9oCrPuDqBb+88lNt54lLdtc947S7sZe2VUtwOWA9aXptVzGy0CFaumOlRz9urVM2UxX+UytnnUSzbSj2PZBpZ4Kl7cW7vEuuNlcE+x9LXlurSVp5WUNJn7IYU314hD6H5hLU2iw2mHFWpyTKEyOTvnk01qWm4I6nhYhpOD7j25arGalUdrL4GUVvIaq5j1QEbyvZqa1ybS1yNkhHKZDdUBivpUChkayp9VUpAh1Hr2oo0nS9TUgTfQEFrS9JNTncNljsUp6rhUua3hP9fw3wnQYsSgmenMHQlj1WMOcXzMPefFYryIZWb9xRS4DF3thezRwBwKet2ISHJl3BFovcGeqf4YkmjJWUsw+DGX4nC4A64bv2kAlemeXIRJV9XPgQLjEzEWIAXeH+JfK+g+1jzNDNAcM+eBWC4LikPxCxWBdJ5WN3xJqBMfMWBVDisCzwDd9BMW7MMZYlNDhFYxCAgGUY5n/1k5ucF9+/+AwTeELeBSQAA"; }
        }
    }
}
