// <auto-generated />
namespace Ms.Cms.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206100338520_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1byW4bNxi+F+g7DOaUFIhGdpvACaQE8RqjsR1YTgr0EtAzlERktpAc1+qr9dBH6iuUnIXiNpskJ5O0N4vLz3/l8s3nf/76e/LqPgqdO4gJSuKpuzcauw6M/SRA8WLqZnT+5MB99fLHHyYnQXTvfKjG7fNxbGZMpu6S0vSF5xF/CSNARhHycUKSOR35SeSBIPH2x+MDb2/sQSbCZbIcZ3KdxRRFMP/Bfh4lsQ9TmoHwIglgSMp21jPLpTqXIIIkBT6cuhdkdBSRUTHQdV6HCDAlZjCc99Ro/Jxr5Iq12GonTCu6ulmlMF9x6h5i5H9ii9wSioFPpy7FGZSnsEm/wpXSwJre4SSFmK6u4bwUdB64jqfO8/SJYpo0h+vC/orps19c5zILQ3AbsoY5CAl0nfTZixlNMDyDMcSAwuAdoBTimM+FuS2lT16kz7q55bk33udu8UAcJxRQFm1DcU3NG0RDWGk6o5hljuuconsYvIXxgi6Fthfgvmp5ytLnfYxYnsHSp5Jxxe/mRX9DAV2KRdmSIbT4p1nGFQ4grmQcrmh/CSxvKfPzl/HAJbhDizwiui9AGLrONQzzTrJEaVEPI97xMU9hViinOImuk7AcXzZ/vAF4ASnTPTH7ZkmGfU2PibeukcbKyZX6v1CUfPuDLb7W9SxDQe+M+y8VW23CVym9WcpXaW1L+aocNkr5NzQKywPjEBBYuotrVbQ2+odP7hlX9mevwHY25Br8mWC7JZKNXqOMC5Bu7IuzlLxN/LKmerlkb7xtrr+BaLGk0n7y835fEb8nSdRDQOewnLFEhXi1sVvPI7CAbxGhDfvlFuqdRCltVK4lY24Sf4vZsyXAMNjYN9L0h/HOzGdHzw2MUrZlfYUb5Bc7bPpuShal/SR+jx96M2y7UNmPFyWKH8tx62PG0m0cN7YxfY6d14QkPsoVk9StzjzVwpM4cBoOwHWFFFfIiyykKA2Rz5aduuPRaM/wmV2i"
                       + "uEUaRauK/Ek3UTKm2Uab4+s0a4zCWkO1IvsZ3xTEFrd29UERff7CAIjdG6sXR5S3I2iaz4fPINXuSOskqt9NLdPL1DZmFxa1TFa8Y5OiuV4TJzlEVUhc7KQRlnufvpc2V4FQXhjtdRNQxVsSUOmn79OqRR2ste4zptWtVdG5LiQj9Og1uKOpDNr82uCVausTyb/Gg7wCEKqAI68GOZqw62fKjg0JSSpbnFkBIx09mfXHi6JChucTC2wktBUrsRcnu3FpvRw1COApwoQeAwpuAT/IjoLIHNZa6tVCcsmawapqrxrN/y7v6DKUNjJf7LLfTpkpEXsq51ZBLbjmtBy6AyHAlhvJURJmUVx3q2maLV7QsgjR2F1OebGRpZRN3WWUj2JZRtnUw57iUaxYUzSZMiaeFgk90p4Raq3e9LzplFW1e2rXtFq/GPvnVs28h0mu4gUuzy9arBJYnQYov598AGGmPv5lEceI+BhFKAbMtIcIa69YSA/77zoYMoAx3GgIiGTgsVDgGFmM0tEjtiXEokS3bOsupUBZZBlFS7cMWcNTw80PBe8ZeI4o2JIiRu7oFhsV5xpufCTAazjRMbwpw3LD9aUA/wbsyTVAOVw/yjDocFxpna1BrrIgratbeBQEeEgROif876v5IzVUuaaPhx6lb/GpVCdD/Vwvi1J7BvP40qCYLbaF+q8PuaS2lGuZP9zUEx8TFDWqxi8faBXzMgEcAXE2oTRiUKedgeN1lg8cGg5qeqJTRHNJtrByR4hl+2lUIogbatRbmfVBck74FyPxdamDnTqI2TvmVqC3UxVXg7vgcRaHN4DBGzpelbiDnGhAlweVG22GtyeJAXjrQ8S2JIBvDeCelGBzO3/SQJ+LIa7DfHCHAo48z1aEwmjEB4xmn8OjELGNcD3gAsRoDgm9ST5BzgUdjw8252EKHhUhQWhB1b86pewWLRC3vpU/1pcQpbLBshh9ziDKpc0Rv9ds87E+vgPYZ/dhgwe2"
                       + "BfELQxBuR/uiKF7lvuwpxCywdp9tQdWw0UW+4UT7jhPDxr/dkYUyH68S+SgC94/7CrKQ2awq5tS1bbhqmgP7MtU2mG4hlFVJ3E+QlX21mSjtsd/k8P2D3gknroHdVfxWGGIPcwBtVDIaA6yHrO6kqY0JRTvjEBVUmn5sISaAxRtiHiQQsu2P/18KMl+p7zCKfZSC0GqBeXvukkzcu0Ku3nMMUxjz3JGN67JOl1eDEK4ld5srevDLunLotmXNlfBkT6LcpmHvHIUto12HN5sLNeAFO49yDYPOYN/UQHHKf9fUEOGKt9PUDW4TFtRiV7Kznaz8vHp6nk1wDbuskX3XTr6zrdRMAftalLV6llorZ8+go+2Ao7czRmKrcrYdxED9HoReZ6IKrB6l/91kOwFBi7UIDpjE0FcqUYw5j+dJtSNoGlVDtIvABaQgYGX6GrM7CfAp6/YhITkfXHzevIXBeXyV0TSjzGQY3YYr2Rl8Y2laP+cQqjpPrtKc970LE5iaiJkAr+LDDIWB0PvUvFLVieA7Vvke5LGk/F24WAlJl0ncUVDpPrHRigq/imfgDtbr1u5D1WOTYwQWGESklLGez36y9Aui+5f/Apb4tjN9PAAA"; }
        }
    }
}
