//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BlModel", "FK_Builder_City", "City", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Bnh.Entities.City), "Builder", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bnh.Entities.Builder), true)]
[assembly: EdmRelationshipAttribute("BlModel", "Community_Builders", "Builder", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bnh.Entities.Builder), "Community", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bnh.Entities.Community))]
[assembly: EdmRelationshipAttribute("BlModel", "FK_Zone_City", "City", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Bnh.Entities.City), "Zone", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bnh.Entities.Zone), true)]
[assembly: EdmRelationshipAttribute("BlModel", "FK_Community_Zone", "Zone", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Bnh.Entities.Zone), "Community", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bnh.Entities.Community), true)]

#endregion

namespace Bnh.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BlEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BlEntities object using the connection string found in the 'BlEntities' section of the application configuration file.
        /// </summary>
        public BlEntities() : this(EntityConnectionHelper.Get("Bl"))
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BlEntities object.
        /// </summary>
        public BlEntities(string connectionString) : base(connectionString, "BlEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BlEntities object.
        /// </summary>
        public BlEntities(EntityConnection connection) : base(connection, "BlEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Builder> Builders
        {
            get
            {
                if ((_Builders == null))
                {
                    _Builders = base.CreateObjectSet<Builder>("Builders");
                }
                return _Builders;
            }
        }
        private ObjectSet<Builder> _Builders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<City> Cities
        {
            get
            {
                if ((_Cities == null))
                {
                    _Cities = base.CreateObjectSet<City>("Cities");
                }
                return _Cities;
            }
        }
        private ObjectSet<City> _Cities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Community> Communities
        {
            get
            {
                if ((_Communities == null))
                {
                    _Communities = base.CreateObjectSet<Community>("Communities");
                }
                return _Communities;
            }
        }
        private ObjectSet<Community> _Communities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Zone> Zones
        {
            get
            {
                if ((_Zones == null))
                {
                    _Zones = base.CreateObjectSet<Zone>("Zones");
                }
                return _Zones;
            }
        }
        private ObjectSet<Zone> _Zones;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Builders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBuilders(Builder builder)
        {
            base.AddObject("Builders", builder);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCities(City city)
        {
            base.AddObject("Cities", city);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Communities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCommunities(Community community)
        {
            base.AddObject("Communities", community);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Zones EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToZones(Zone zone)
        {
            base.AddObject("Zones", zone);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlModel", Name="Builder")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Builder : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Builder object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="cityId">Initial value of the CityId property.</param>
        /// <param name="urlId">Initial value of the UrlId property.</param>
        public static Builder CreateBuilder(global::System.Guid id, global::System.String name, global::System.Guid cityId, global::System.String urlId)
        {
            Builder builder = new Builder();
            builder.Id = id;
            builder.Name = name;
            builder.CityId = cityId;
            builder.UrlId = urlId;
            return builder;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CityId
        {
            get
            {
                return _CityId;
            }
            set
            {
                OnCityIdChanging(value);
                ReportPropertyChanging("CityId");
                _CityId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CityId");
                OnCityIdChanged();
            }
        }
        private global::System.Guid _CityId;
        partial void OnCityIdChanging(global::System.Guid value);
        partial void OnCityIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UrlId
        {
            get
            {
                return _UrlId;
            }
            set
            {
                OnUrlIdChanging(value);
                ReportPropertyChanging("UrlId");
                _UrlId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UrlId");
                OnUrlIdChanged();
            }
        }
        private global::System.String _UrlId;
        partial void OnUrlIdChanging(global::System.String value);
        partial void OnUrlIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlModel", "FK_Builder_City", "City")]
        public City City
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<City>("BlModel.FK_Builder_City", "City").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<City>("BlModel.FK_Builder_City", "City").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<City> CityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<City>("BlModel.FK_Builder_City", "City");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<City>("BlModel.FK_Builder_City", "City", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlModel", "Community_Builders", "Community")]
        public EntityCollection<Community> Communities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Community>("BlModel.Community_Builders", "Community");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Community>("BlModel.Community_Builders", "Community", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlModel", Name="City")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class City : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new City object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="urlId">Initial value of the UrlId property.</param>
        public static City CreateCity(global::System.Guid id, global::System.String name, global::System.String urlId)
        {
            City city = new City();
            city.Id = id;
            city.Name = name;
            city.UrlId = urlId;
            return city;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UrlId
        {
            get
            {
                return _UrlId;
            }
            set
            {
                OnUrlIdChanging(value);
                ReportPropertyChanging("UrlId");
                _UrlId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UrlId");
                OnUrlIdChanged();
            }
        }
        private global::System.String _UrlId;
        partial void OnUrlIdChanging(global::System.String value);
        partial void OnUrlIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlModel", "FK_Builder_City", "Builder")]
        public EntityCollection<Builder> Builders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Builder>("BlModel.FK_Builder_City", "Builder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Builder>("BlModel.FK_Builder_City", "Builder", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlModel", "FK_Zone_City", "Zone")]
        public EntityCollection<Zone> Zones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Zone>("BlModel.FK_Zone_City", "Zone");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Zone>("BlModel.FK_Zone_City", "Zone", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlModel", Name="Community")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Community : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Community object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="zoneId">Initial value of the ZoneId property.</param>
        /// <param name="urlId">Initial value of the UrlId property.</param>
        /// <param name="remoteness">Initial value of the Remoteness property.</param>
        /// <param name="hasLake">Initial value of the HasLake property.</param>
        /// <param name="hasWaterFeature">Initial value of the HasWaterFeature property.</param>
        /// <param name="hasClubOrFacility">Initial value of the HasClubOrFacility property.</param>
        /// <param name="hasMountainView">Initial value of the HasMountainView property.</param>
        /// <param name="hasParksAndPathways">Initial value of the HasParksAndPathways property.</param>
        /// <param name="hasShoppingPlaza">Initial value of the HasShoppingPlaza property.</param>
        public static Community CreateCommunity(global::System.Guid id, global::System.String name, global::System.Guid zoneId, global::System.String urlId, global::System.Int32 remoteness, global::System.Boolean hasLake, global::System.Boolean hasWaterFeature, global::System.Boolean hasClubOrFacility, global::System.Boolean hasMountainView, global::System.Boolean hasParksAndPathways, global::System.Boolean hasShoppingPlaza)
        {
            Community community = new Community();
            community.Id = id;
            community.Name = name;
            community.ZoneId = zoneId;
            community.UrlId = urlId;
            community.Remoteness = remoteness;
            community.HasLake = hasLake;
            community.HasWaterFeature = hasWaterFeature;
            community.HasClubOrFacility = hasClubOrFacility;
            community.HasMountainView = hasMountainView;
            community.HasParksAndPathways = hasParksAndPathways;
            community.HasShoppingPlaza = hasShoppingPlaza;
            return community;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ZoneId
        {
            get
            {
                return _ZoneId;
            }
            set
            {
                OnZoneIdChanging(value);
                ReportPropertyChanging("ZoneId");
                _ZoneId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ZoneId");
                OnZoneIdChanged();
            }
        }
        private global::System.Guid _ZoneId;
        partial void OnZoneIdChanging(global::System.Guid value);
        partial void OnZoneIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UrlId
        {
            get
            {
                return _UrlId;
            }
            set
            {
                OnUrlIdChanging(value);
                ReportPropertyChanging("UrlId");
                _UrlId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UrlId");
                OnUrlIdChanged();
            }
        }
        private global::System.String _UrlId;
        partial void OnUrlIdChanging(global::System.String value);
        partial void OnUrlIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GpsLocation
        {
            get
            {
                return _GpsLocation;
            }
            set
            {
                OnGpsLocationChanging(value);
                ReportPropertyChanging("GpsLocation");
                _GpsLocation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GpsLocation");
                OnGpsLocationChanged();
            }
        }
        private global::System.String _GpsLocation;
        partial void OnGpsLocationChanging(global::System.String value);
        partial void OnGpsLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GpsBounds
        {
            get
            {
                return _GpsBounds;
            }
            set
            {
                OnGpsBoundsChanging(value);
                ReportPropertyChanging("GpsBounds");
                _GpsBounds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GpsBounds");
                OnGpsBoundsChanged();
            }
        }
        private global::System.String _GpsBounds;
        partial void OnGpsBoundsChanging(global::System.String value);
        partial void OnGpsBoundsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        [FilterableProperty(Title="To city center", Operator=FilterOperator.LessOrEqual)]
        public global::System.Int32 Remoteness
        {
            get
            {
                return _Remoteness;
            }
            set
            {
                OnRemotenessChanging(value);
                ReportPropertyChanging("Remoteness");
                _Remoteness = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Remoteness");
                OnRemotenessChanged();
            }
        }
        private global::System.Int32 _Remoteness;
        partial void OnRemotenessChanging(global::System.Int32 value);
        partial void OnRemotenessChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        [FilterableProperty(Title="Has Lake")]
        public global::System.Boolean HasLake
        {
            get
            {
                return _HasLake;
            }
            set
            {
                OnHasLakeChanging(value);
                ReportPropertyChanging("HasLake");
                _HasLake = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasLake");
                OnHasLakeChanged();
            }
        }
        private global::System.Boolean _HasLake;
        partial void OnHasLakeChanging(global::System.Boolean value);
        partial void OnHasLakeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        [FilterableProperty(Title = "Has Water Feature")]
        public global::System.Boolean HasWaterFeature
        {
            get
            {
                return _HasWaterFeature;
            }
            set
            {
                OnHasWaterFeatureChanging(value);
                ReportPropertyChanging("HasWaterFeature");
                _HasWaterFeature = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasWaterFeature");
                OnHasWaterFeatureChanged();
            }
        }
        private global::System.Boolean _HasWaterFeature;
        partial void OnHasWaterFeatureChanging(global::System.Boolean value);
        partial void OnHasWaterFeatureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        [FilterableProperty(Title = "Has Club Or Facility")]
        public global::System.Boolean HasClubOrFacility
        {
            get
            {
                return _HasClubOrFacility;
            }
            set
            {
                OnHasClubOrFacilityChanging(value);
                ReportPropertyChanging("HasClubOrFacility");
                _HasClubOrFacility = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasClubOrFacility");
                OnHasClubOrFacilityChanged();
            }
        }
        private global::System.Boolean _HasClubOrFacility;
        partial void OnHasClubOrFacilityChanging(global::System.Boolean value);
        partial void OnHasClubOrFacilityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        [FilterableProperty(Title = "Has Mountain View")]
        public global::System.Boolean HasMountainView
        {
            get
            {
                return _HasMountainView;
            }
            set
            {
                OnHasMountainViewChanging(value);
                ReportPropertyChanging("HasMountainView");
                _HasMountainView = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasMountainView");
                OnHasMountainViewChanged();
            }
        }
        private global::System.Boolean _HasMountainView;
        partial void OnHasMountainViewChanging(global::System.Boolean value);
        partial void OnHasMountainViewChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        [FilterableProperty(Title = "Has Parks And Pathways")]
        public global::System.Boolean HasParksAndPathways
        {
            get
            {
                return _HasParksAndPathways;
            }
            set
            {
                OnHasParksAndPathwaysChanging(value);
                ReportPropertyChanging("HasParksAndPathways");
                _HasParksAndPathways = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasParksAndPathways");
                OnHasParksAndPathwaysChanged();
            }
        }
        private global::System.Boolean _HasParksAndPathways;
        partial void OnHasParksAndPathwaysChanging(global::System.Boolean value);
        partial void OnHasParksAndPathwaysChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        [FilterableProperty(Title = "Has Shopping Plaza")]
        public global::System.Boolean HasShoppingPlaza
        {
            get
            {
                return _HasShoppingPlaza;
            }
            set
            {
                OnHasShoppingPlazaChanging(value);
                ReportPropertyChanging("HasShoppingPlaza");
                _HasShoppingPlaza = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasShoppingPlaza");
                OnHasShoppingPlazaChanged();
            }
        }
        private global::System.Boolean _HasShoppingPlaza;
        partial void OnHasShoppingPlazaChanging(global::System.Boolean value);
        partial void OnHasShoppingPlazaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlModel", "Community_Builders", "Builder")]
        public EntityCollection<Builder> Builders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Builder>("BlModel.Community_Builders", "Builder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Builder>("BlModel.Community_Builders", "Builder", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlModel", "FK_Community_Zone", "Zone")]
        public Zone Zone
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Zone>("BlModel.FK_Community_Zone", "Zone").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Zone>("BlModel.FK_Community_Zone", "Zone").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Zone> ZoneReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Zone>("BlModel.FK_Community_Zone", "Zone");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Zone>("BlModel.FK_Community_Zone", "Zone", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlModel", Name="Zone")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Zone : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Zone object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="cityId">Initial value of the CityId property.</param>
        /// <param name="urlId">Initial value of the UrlId property.</param>
        public static Zone CreateZone(global::System.Guid id, global::System.String name, global::System.Guid cityId, global::System.String urlId)
        {
            Zone zone = new Zone();
            zone.Id = id;
            zone.Name = name;
            zone.CityId = cityId;
            zone.UrlId = urlId;
            return zone;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CityId
        {
            get
            {
                return _CityId;
            }
            set
            {
                OnCityIdChanging(value);
                ReportPropertyChanging("CityId");
                _CityId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CityId");
                OnCityIdChanged();
            }
        }
        private global::System.Guid _CityId;
        partial void OnCityIdChanging(global::System.Guid value);
        partial void OnCityIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _Order;
        partial void OnOrderChanging(Nullable<global::System.Int32> value);
        partial void OnOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UrlId
        {
            get
            {
                return _UrlId;
            }
            set
            {
                OnUrlIdChanging(value);
                ReportPropertyChanging("UrlId");
                _UrlId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UrlId");
                OnUrlIdChanged();
            }
        }
        private global::System.String _UrlId;
        partial void OnUrlIdChanging(global::System.String value);
        partial void OnUrlIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlModel", "FK_Zone_City", "City")]
        public City City
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<City>("BlModel.FK_Zone_City", "City").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<City>("BlModel.FK_Zone_City", "City").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<City> CityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<City>("BlModel.FK_Zone_City", "City");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<City>("BlModel.FK_Zone_City", "City", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlModel", "FK_Community_Zone", "Community")]
        public EntityCollection<Community> Communities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Community>("BlModel.FK_Community_Zone", "Community");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Community>("BlModel.FK_Community_Zone", "Community", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
